dataset: OpenNQ
target_model:
  model_safename: phi_4
  config: 
    model_type: hf
    model_name: microsoft/phi-4
  generation_config:
    max_new_tokens: 100 
    temperature: 0.1 #Important since standard answer
    do_sample: True
  generate_function_parameters:
    verbose_inputs: True
    verbose_outputs: True
  generate_function_kwargs: 
    batch_size: 7 #TODO test
  random_seed: 42
