dataset: TriviaQA
ensembling_method: clarification_zeroshot
variation_model:
  model_safename: gpt_4o
target_model:
  model_safename: llama4_maverick
uncertainty_metric: all
kernel_gamma: 1.0
embedding_model:
  model_safename: all_mpnet_base_v2
  model_name: all-mpnet-base-v2
  batch_size: 40000
  encoding_arguments:
    batch_size: 256
    convert_to_numpy: true
    convert_to_tensor: false
