dataset: AmbigInst
ensembling_method: clarification_zeroshot
variation_model: 
  model_safename: gpt_4o 
target_model:
  model_safename: phi_4
  config: 
    model_type: hf
    model_name: microsoft/phi-4
  generation_config:
    max_new_tokens: 600 
    temperature: 0.5
    do_sample: True
  generate_function_parameters:
    verbose_inputs: True
    verbose_outputs: True
  generate_function_kwargs: 
    batch_size: 10 #TODO test
  random_seed: 42
answer_per_variant: 10
